export const projects = [
  "Everyday actions",
  "Workshop sequences",
  "Language prompts",
];
export const reviewers = ["REV-01", "REV-02", "REV-03"];

// Wholly invented metadata. These records do not refer to people or actual media.
const seed = [
  [
    "FW-1041",
    "CTR-024",
    "Everyday actions",
    "Organize a shelf",
    "Video sequence",
    "Submitted",
    "",
    "Today",
    8,
  ],
  [
    "FW-1042",
    "CTR-017",
    "Workshop sequences",
    "Sort hand tools",
    "Video sequence",
    "In review",
    "REV-01",
    "Today",
    12,
  ],
  [
    "FW-1043",
    "CTR-036",
    "Language prompts",
    "Read a short instruction",
    "Audio prompt",
    "Submitted",
    "REV-02",
    "Today",
    6,
  ],
  [
    "FW-1044",
    "CTR-011",
    "Everyday actions",
    "Fold a fabric sample",
    "Video sequence",
    "Changes requested",
    "REV-03",
    "Tomorrow",
    9,
  ],
  [
    "FW-1045",
    "CTR-029",
    "Workshop sequences",
    "Arrange labeled containers",
    "Video sequence",
    "In progress",
    "",
    "Tomorrow",
    10,
  ],
  [
    "FW-1046",
    "CTR-008",
    "Language prompts",
    "Describe a simple object",
    "Audio prompt",
    "Accepted",
    "REV-02",
    "Complete",
    7,
  ],
  [
    "FW-1047",
    "CTR-042",
    "Everyday actions",
    "Stack reusable boxes",
    "Video sequence",
    "Ready",
    "",
    "Tomorrow",
    8,
  ],
  [
    "FW-1048",
    "CTR-031",
    "Workshop sequences",
    "Wipe a clear work surface",
    "Video sequence",
    "Submitted",
    "",
    "Today",
    11,
  ],
  [
    "FW-1049",
    "CTR-015",
    "Language prompts",
    "Read a location-neutral phrase",
    "Audio prompt",
    "In review",
    "REV-03",
    "Today",
    5,
  ],
  [
    "FW-1050",
    "CTR-047",
    "Everyday actions",
    "Place objects in a tray",
    "Video sequence",
    "Accepted",
    "REV-01",
    "Complete",
    10,
  ],
  [
    "FW-1051",
    "CTR-022",
    "Workshop sequences",
    "Group materials by shape",
    "Video sequence",
    "Ready",
    "",
    "Later",
    9,
  ],
  [
    "FW-1052",
    "CTR-039",
    "Language prompts",
    "Speak an action instruction",
    "Audio prompt",
    "Changes requested",
    "REV-02",
    "Tomorrow",
    6,
  ],
];

export function createDemoRecords() {
  return seed.map(
    ([
      id,
      contributor,
      project,
      title,
      type,
      status,
      reviewer,
      due,
      units,
    ]) => ({
      id,
      contributor,
      project,
      title,
      type,
      status,
      reviewer,
      due,
      units,
      note:
        status === "Changes requested"
          ? "Illustrative review note: clarify the sequence and repeat the final step."
          : status === "Accepted"
            ? "Illustrative review note: the described steps meet the sample task instructions."
            : "",
      history: [{ label: `Demo initialized: ${status}`, at: "Seed record" }],
    }),
  );
}
